VerinFast/verinfast

- verinfast/agent.py
All new changes will have tickets and corresponding branches
> Last changes from initial-prototype branch

- requirements.txt
- verinfast/agent.py
- verinfast/cloud/aws/aws.py
- verinfast/cloud/az_parse.py
- verinfast/utils/utils.py
Fixed TL uploads
And debug logging was creating multiple log.txt files because of the chdir for repos. Fixed.
> Fixes for uploading to TL, and debug logging

- .flake8
- src/verinfast/agent.py
- src/verinfast/cloud/aws/blocks.py
- src/verinfast/cloud/aws/instances.py
AWS blocks wasn't working. Testing with TL account. Made some fixes.
> Fixes for aws blocks

- src/verinfast/agent.py
> fix bug where relative path can't split

- src/verinfast/agent.py
- src/verinfast/cloud/aws/costs.py
- src/verinfast/config.py
I've got a lot of profiles, and original code crashed for various reasons while trying to loop through them/
I believe it make sense to add this setting, when user knows which profile to use to scan the account.
Side effect = scan speedup.
> Adding support for cloud profile config, to avoid looping.

- Dockerfile
I needed a docker container to run scans.  I thought this might save someone the trouble in the future.
> a simple Dockerfile based on alpine

- src/verinfast/config.py
- src/verinfast/config.yaml
> added run_git to config

- .github/workflows/release.yml
- src/verinfast/agent.py
- tests/str_conf.yaml
- tests/test_local.py
- tests/test_yaml.py
Fixes bug for remote repos with no .git (Azure) and local repos with no .git in folder name.
> support no dot git

- CODE_OF_CONDUCT.md
- README.md
@aylusltd Added the Code of conduct from contributor covenant.
Please provide a contact method to replace the placeholder.
Let me know what you think
> add a code of conduct

- .github/PULL_REQUEST_TEMPLATE.md
Closes #182 
@aylusltd   Please, let me know if there any changes to be made.
> Add Pull request Template #182

- src/verinfast/dependencies/walk.py
- src/verinfast/dependencies/walkers/README.md
- tests/requirements.txt
- tests/test_dependency.py
Adds tests for the python walker parsing requirements.txt files and confirms the output in `tests/dependencies.json`
> Test python walker

- tests/delete_temp.yaml
- tests/test_print_cloud_provider.py
Closing ticket related to cloud print error.
SOS-625 (internal ticket)
> confirmed printable cloud

- src/verinfast/dependencies/walkers/README.md
- tests/requirements.txt
- tests/test_dependency.py
Mark (@mnyon-grandkru) submitted these, I just merged it into a branch to let it have access to secrets. It creates a working requirements.txt file and runs our test suite against it. I thought we already had that covered, but good catch on his part.
- [?] I've made sure all auto checks have passed. (doing that now, yeah?)
> External pr2

- src/verinfast/agent.py
This is a copy of Pull Request 219. I messed up a rebase of that branch and this is to clean up the commits.
> add branch

- src/verinfast/agent.py
Capturing the branch scanned currently breaks data collection. Once that is fixed we can re-add this to line 347 of agent.py
```
"branch": locals()['branch'] if "branch" in locals() else None
```
- [x ] I've made sure all auto checks have passed.
> removed capturing branch

- src/verinfast/agent.py
- src/verinfast/cloud/aws/costs.py
fixed some bugs with preflight undefined variables.
> Aws no paginate, and preflight fixes

- src/verinfast/cloud/azure/costs.py
This fixes a bug reported by a user with a trailing \r\n in windows.
> strip all surrounging whitespace

- requirements.txt
- src/verinfast/agent.py
- src/verinfast/cloud/aws/costs.py
Address bugs in 3 recent scans
> Better error handling

- src/verinfast/agent.py
- src/verinfast/user.py
Users often make multiple runs, especially after something errors out. Sometimes there are remnants from a previous run. This allows the user to remove that remnant without having to restart.
TEC-197
> abstract prompting, delete temp_dir

- src/verinfast/agent.py
- src/verinfast/user.py
- src/verinfast/utils/utils.py
Fixed a bug where the preflight prompt was not asking a question before showing `(Y/n)` and made the prompting easier to read.
> Preflight prompt fix

- requirements.txt
https://github.com/StartupOS/verinfast/pull/334#issuecomment-2048870868
Removed protobuf. Uninstalled VF and protobuf, ran a clean install. Ran a scan with repos, AWS, and GCP. It all worked.
> Removed protobuf

- src/verinfast/cloud/aws/instances.py
AWS returns data that causes "ERROR: list index out of range"
> AWS Instances "ERROR: list index out of range" fix

- .gitignore
- src/verinfast/agent.py
- src/verinfast/dependencies/walk.py
- src/verinfast/dependencies/walkers/composer.py
- tests/composer.json
- tests/composer.yaml
- tests/test_dependency.py
Adds support for composer projects 
[SOS-676](https://nichols.atlassian.net/browse/SOS-676?atlOrigin=eyJpIjoiOTkwOWMyNTYyMjc4NDQxNmFhNTdjMmNmM2I1ODkzYTUiLCJwIjoiaiJ9)
[SOS-676]: https://nichols.atlassian.net/browse/SOS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add PHP walker

- .github/workflows/release.yml
> Update action versions

- src/verinfast/config.py
Setting the default date missed the condition for June, ie month 6 and setting the date to 6 month ago
> Default date creation fixed

- .gitignore
I have an SLN file I don't want to delete but don't want in the repo yet. Might prove useful testing nuget stuff later.
> ignore sln

- src/verinfast/agent.py
- tests/test_dependency.py
Removed some commented code, added a try catch
Reduces redundancy and file length
N/A
> Updates to html
